#####################################################################################
# Application config
#####################################################################################
server.port=8040
#####################################################################################
# GCP config
#####################################################################################
gcp.project-id=prj-ext-dev-intervene-413412
gcp.region=EUROPE_WEST2
gcp.secret-manager.config.ttl=1800
#2592000
#####################################################################################
# Crypt4gh config
#####################################################################################
crypt4gh.shell-path=/bin/zsh -c
crypt4gh.binary-path=/Users/ashutosh/.local/bin/crypt4gh-keygen
crypt4gh.keys.base-path=/Users/ashutosh/crypt4gh/key-test
crypt4gh.private-key.password=${SEC_PASSWD:test-password}
#####################################################################################
# Spring Security OAuth2 client registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
