#####################################################################################
# Application config
#####################################################################################
server.port=8040
#####################################################################################
# GCP config
#####################################################################################
gcp.project-id=prj-ext-dev-intervene-413412
gcp.secret.path-prefix=projects/968549395092/secrets
gcp.region=EUROPE_WEST2
gcp.secret-manager.config.ttl=2592000
#2592000
#####################################################################################
# Crypt4gh config
#####################################################################################
crypt4gh.shell-path=@crypt4gh.shell-path@
crypt4gh.binary-path=@crypt4gh.binary-path@
crypt4gh.keys.base-path=@crypt4gh.keys.base-path@
crypt4gh.private-key.password=${SEC_KEY_PASSWD}
#####################################################################################
# Spring Security OAuth2 client registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.aai.lifescience-ri.eu/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.aai.lifescience-ri.eu/oidc/jwk
#####################################################################################
# Basic authentication
#####################################################################################
basic.auth.username=@basic.auth.username@
basic.auth.password=@basic.auth.password@
#####################################################################################
# Internal service config
#####################################################################################
intervene.user-manager.base-url=http://localhost:8030/user-manager
intervene.user-manager.user-account.uri=/user/account
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
#####################################################################################
# Swagger config
#####################################################################################
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml
