variables:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -s ci_settings.xml'
  SKIP_TESTS: '-DskipTests=true -Djacoco.skip=true'
  CACHE_KEY: $CI_COMMIT_REF_SLUG
  INTERVENE_COMMONS_MODULE: 'intervene-commons'
  FILE_HANDLER_MODULE: 'file-handler'
  PIPELINE_MANAGER_MODULE: 'pipeline-manager'
  USER_MANAGER_MODULE: 'user-manager'

cache:
  key: $CACHE_KEY
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - containerize
  - deploy

.build-module:
  stage: build
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo "Building $MODULE"'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE package $SKIP_TESTS --also-make'
  artifacts:
    paths:
      - '*/target'
    expire_in: 30 min

.test-module:
  stage: test
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo Testing $MODULE'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE surefire:test --also-make'

.containerize-module:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --build-arg "MODULE_NAME=${MODULE}"
      --destination "${CI_REGISTRY_IMAGE}:${MODULE}-${CI_COMMIT_TAG}-dev"
  only:
    - /^\d+\.\d+\.\d+$/
    - tags

.deploy-module:
  stage: deploy
  image: bitnami/kubectl:latest #change to stable version
  id_tokens:
    GCP_ID_TOKEN:
      aud: https://iam.googleapis.com/projects/968549395092/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  secrets:
    IGS4EU_PLATFORM_SECRET:
      gcp_secret_manager:
        name: igs4eu-platform-secret
      token: $GCP_ID_TOKEN
  variables:
    K8S_CLUSTER_AGENT: gdp/ga4k:k8s-agent
  script:
    - kubectl config get-contexts
    - kubectl config use-context $K8S_CLUSTER_AGENT
    - kubectl -n intervene-dev get pods
    - echo $IGS4EU_PLATFORM_SECRET
  #   - sed "s/\$NAMESPACE/intervene-dev/; s/\$TAG/$CI_COMMIT_TAG/"
  #   - kubectl -f $MODULE/deployments/
 #only:
 #  - /^\d+\.\d+\.\d+$/
#   - tags

build-intervene-commons-module:
  variables:
    MODULE: $INTERVENE_COMMONS_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$INTERVENE_COMMONS_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

build-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$FILE_HANDLER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .containerize-module

deploy-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .deploy-module
# needs:
#   - 'containerize-file-handler-module'

build-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$PIPELINE_MANAGER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .containerize-module

deploy-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .deploy-module
# needs:
#   - 'containerize-pipeline-manager-module'

build-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$USER_MANAGER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .containerize-module

deploy-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .deploy-module
# needs:
#   - 'containerize-user-manager-module'
