variables:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -s ci_settings.xml'
  SKIP_TESTS: '-DskipTests=true -Djacoco.skip=true'
  CACHE_KEY: $CI_COMMIT_REF_SLUG
  INTERVENE_COMMONS_MODULE: 'intervene-commons'
  FILE_HANDLER_MODULE: 'file-handler'
  PIPELINE_MANAGER_MODULE: 'pipeline-manager'
  USER_MANAGER_MODULE: 'user-manager'
  KEY_HANDLER_MODULE: 'key-handler'
  GENERIC_DOCKER_FILE: 'docker/Dockerfile'
  KEY_HANDLER_DOCKER_FILE: 'docker/key-handler/Dockerfile'
  TARGET_PLATFORM: 'linux/amd64'
  TAG_REGEX: '/^\d+\.\d+\.\d+$/'
  STAGE: "BUILD_TEST_CONTAINERIZE"
  DEPLOY_STAGE: "DEPLOY"

cache:
  key: $CACHE_KEY
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - containerize
  - deploy

.build-module:
  stage: build
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo "Building $MODULE"'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE install $SKIP_TESTS --also-make'
  artifacts:
    paths:
      - '*/target'
    expire_in: 30 min
  rules:
    # Skip if STAGE is set to DEPLOY
    - if: '$STAGE == $DEPLOY_STAGE'
      when: never
    # Run if STAGE is not DEPLOY and there are changes
    - if: '$STAGE != $DEPLOY_STAGE'
      changes:
        - '$FILE_HANDLER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml
      when: on_success

.test-module:
  stage: test
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo Testing $MODULE'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE -am surefire:test'
  rules:
    - if: '$STAGE != $DEPLOY_STAGE'  # Skip if STAGE is set to "deploy"
      when: always

.containerize-module:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${DOCKER_FILE}"
      --build-arg "MODULE_NAME=${MODULE}"
      --build-arg "TARGET_PLATFORM=${TARGET_PLATFORM}"
      --destination "${CI_REGISTRY_IMAGE}:${MODULE}-${CI_COMMIT_TAG}-dev"
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE != $DEPLOY_STAGE'
      when: always

.deploy-module:
  stage: deploy
  image: alpine/k8s:1.32.0
  variables:
    K8S_CLUSTER_AGENT: gdp/ga4k:gcp-k8s-agent
    ENV_FILE: 'gcp-dev-env'
    GCP_PROJECT_ID: '968549395092'
  id_tokens:
    GCP_ID_TOKEN:
      # Keep same names/location in diff. envs.
      aud: https://iam.googleapis.com/projects/${GCP_PROJECT_ID}/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  secrets:
    BASIC_AUTH_SEC_PASSWD_SECRET:
      gcp_secret_manager:
        name: basic-auth-sec-passwd-secret
      token: $GCP_ID_TOKEN
    DATABASE_SECRET:
      gcp_secret_manager:
        name: database-secret
      token: $GCP_ID_TOKEN
    EGA_AAI_SECRET:
      gcp_secret_manager:
        name: ega-aai-secret
      token: $GCP_ID_TOKEN
    EMAIL_SECRET:
      gcp_secret_manager:
        name: email-secret
      token: $GCP_ID_TOKEN
    GLOBUS_AUTH_SECRET:
      gcp_secret_manager:
        name: globus-auth-secret
      token: $GCP_ID_TOKEN
    S3_SECRET:
      gcp_secret_manager:
        name: s3-secret
      token: $GCP_ID_TOKEN
  script:
    - kubectl config get-contexts
    - kubectl config use-context $K8S_CLUSTER_AGENT
    - kubectl -n intervene-dev get pods
    - 'echo "K8S_CLUSTER_AGENT: $K8S_CLUSTER_AGENT"'
    - 'echo "MODULE: $MODULE"'
    - 'echo "ENV_FILE: $ENV_FILE"'
    - 'echo "KUBE_NAMESPACE: $KUBE_NAMESPACE"'
    - 'echo "CI_COMMIT_TAG: $CI_COMMIT_TAG"'
    - 'echo "MODULE NAME:" ${MODULE}'
    - 'ls -l ./${MODULE}/deployments'
    - helm upgrade --install ${MODULE} ./${MODULE}/deployments -f values-${ENV_FILE} \
      --namespace $KUBE_NAMESPACE \
      --set image.tag=$CI_COMMIT_TAG
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $DEPLOY_STAGE'
      when: always

build-intervene-commons-module:
  variables:
    MODULE: $INTERVENE_COMMONS_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$INTERVENE_COMMONS_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

build-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$FILE_HANDLER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

test-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .test-module
  dependencies:
    - 'build-file-handler-module'

containerize-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

deploy-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .deploy-module

build-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$PIPELINE_MANAGER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

build-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$USER_MANAGER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

build-key-handler-module:
  variables:
    MODULE: $KEY_HANDLER_MODULE
  extends:
    - .build-module
  rules:
    - changes:
        - '$KEY_HANDLER_MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml

containerize-key-handler-module:
  variables:
    MODULE: $KEY_HANDLER_MODULE
    DOCKER_FILE: $KEY_HANDLER_DOCKER_FILE
  extends:
    - .containerize-module
