# Global variables
variables:
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -s ci_settings.xml'
  SKIP_TESTS: '-DskipTests=true -Djacoco.skip=true'
  CACHE_KEY: $CI_COMMIT_REF_SLUG
  INTERVENE_COMMONS_MODULE: 'intervene-commons'
  FILE_HANDLER_MODULE: 'file-handler'
  PIPELINE_MANAGER_MODULE: 'pipeline-manager'
  USER_MANAGER_MODULE: 'user-manager'
  KEY_HANDLER_MODULE: 'key-handler'
  GENERIC_DOCKER_FILE: 'docker/Dockerfile'
  KEY_HANDLER_DOCKER_FILE: 'docker/key-handler/Dockerfile'
  TARGET_PLATFORM: 'linux/amd64'
  TAG_REGEX: '/^\d+\.\d+\.\d+$/'
  STAGE: "BUILD_TEST_CONTAINERIZE"
  DEPLOY_STAGE: "DEPLOY"

# Cache path
cache:
  key: $CACHE_KEY
  paths:
    - .m2/repository/

# Pipeline stages
stages:
  - build
  - test
  - containerize
  - deploy

# Generic build stage
.build-module:
  stage: build
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo "Building $MODULE"'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE install $SKIP_TESTS --also-make'
  artifacts:
    paths:
      - '*/target'
    expire_in: 30 min
  rules:
    - if: '$STAGE != $DEPLOY_STAGE'  # Skip if STAGE is set to "DEPLOY"
      changes:
        - '$MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml
      when: always

# Generic test stage
.test-module:
  stage: test
  image: maven:3.8.7-eclipse-temurin-19
  script:
    - 'echo Testing $MODULE'
    - 'mvn $MAVEN_CLI_OPTS -pl $MODULE -am surefire:test'
  rules:
    - if: '$STAGE != $DEPLOY_STAGE'  # Skip if STAGE is set to "DEPLOY"
      changes:
        - '$MODULE/**/*'
        - pom.xml
        - .gitlab-ci.yml
      when: always

# Generic containerize stage
.containerize-module:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${DOCKER_FILE}"
      --build-arg "MODULE_NAME=${MODULE}"
      --build-arg "TARGET_PLATFORM=${TARGET_PLATFORM}"
      --destination "${CI_REGISTRY_IMAGE}:${MODULE}-${CI_COMMIT_TAG}-dev"
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE != $DEPLOY_STAGE'
      when: always

# Generic deploy stage
.deploy-module:
  stage: deploy
  image: alpine/k8s:1.32.0
  variables:
    K8S_CLUSTER_AGENT: gdp/ga4k:gcp-k8s-agent
    ENV_FILE: 'gcp-dev-env'
    GCP_PROJECT_ID: '968549395092'
    DEFAULT_NAMESPACE: 'intervene-dev'
  id_tokens:
    GCP_ID_TOKEN:
      # Keep same names/location in diff. envs.
      aud: https://iam.googleapis.com/projects/${GCP_PROJECT_ID}/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  secrets:
    BASIC_AUTH_SEC_PASSWD_SECRET:
      gcp_secret_manager:
        name: basic-auth-sec-passwd-secret
      token: $GCP_ID_TOKEN
    DATABASE_SECRET:
      gcp_secret_manager:
        name: database-secret
      token: $GCP_ID_TOKEN
    EGA_AAI_SECRET:
      gcp_secret_manager:
        name: ega-aai-secret
      token: $GCP_ID_TOKEN
    EMAIL_SECRET:
      gcp_secret_manager:
        name: email-secret
      token: $GCP_ID_TOKEN
    GLOBUS_AUTH_SECRET:
      gcp_secret_manager:
        name: globus-auth-secret
      token: $GCP_ID_TOKEN
    S3_SECRET:
      gcp_secret_manager:
        name: s3-secret
      token: $GCP_ID_TOKEN
  script:
    - kubectl config get-contexts
    - kubectl config use-context $K8S_CLUSTER_AGENT
    - kubectl -n $DEFAULT_NAMESPACE get pods
    - mv $BASIC_AUTH_SEC_PASSWD_SECRET "$BASIC_AUTH_SEC_PASSWD_SECRET".yaml
    - mv $DATABASE_SECRET "$DATABASE_SECRET".yaml
    - mv $EGA_AAI_SECRET "$EGA_AAI_SECRET".yaml
    - mv $EMAIL_SECRET "$EMAIL_SECRET".yaml
    - mv $GLOBUS_AUTH_SECRET "$GLOBUS_AUTH_SECRET".yaml
    - mv $S3_SECRET "$S3_SECRET".yaml
    - SECRET_FILES_PATH=$(dirname "$BASIC_AUTH_SEC_PASSWD_SECRET")
    - kubectl -n $DEFAULT_NAMESPACE apply -f "$SECRET_FILES_PATH"/
    - |
      helm upgrade --install "${MODULE}" "./${MODULE}/deployments" -f "./${MODULE}/deployments/values-${ENV_FILE}.yaml" \
      --namespace "$DEFAULT_NAMESPACE" \
      --set image.tag="$CI_COMMIT_TAG"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $DEPLOY_STAGE'
      when: always

# Commons library build stage
build-intervene-commons-module:
  variables:
    MODULE: $INTERVENE_COMMONS_MODULE
  extends:
    - .build-module

# File handler build stage
build-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .build-module

# File handler test stage
test-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .test-module
  needs:
    - job: build-file-handler-module  # Ensures the build job completes first
      artifacts: true

# File handler containerize stage
containerize-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

# File handler deploy stage
deploy-file-handler-module:
  variables:
    MODULE: $FILE_HANDLER_MODULE
  extends:
    - .deploy-module

# Pipeline manager build stage
build-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .build-module

# Pipeline manager test stage
test-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
  extends:
    - .test-module
  needs:
    - job: build-pipeline-manager-module  # Ensures the build job completes first
      artifacts: true

# Pipeline manager containerize stage
containerize-pipeline-manager-module:
  variables:
    MODULE: $PIPELINE_MANAGER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

# User manager build stage
build-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .build-module

# User manager test stage
test-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
  extends:
    - .test-module
  needs:
    - job: build-user-manager-module  # Ensures the build job completes first
      artifacts: true

# User manager containerize stage
containerize-user-manager-module:
  variables:
    MODULE: $USER_MANAGER_MODULE
    DOCKER_FILE: $GENERIC_DOCKER_FILE
  extends:
    - .containerize-module

# Key handler build stage
build-key-handler-module:
  variables:
    MODULE: $KEY_HANDLER_MODULE
  extends:
    - .build-module

# Key handler test stage
test-key-handler-module:
  variables:
    MODULE: $KEY_HANDLER_MODULE
  extends:
    - .test-module
  needs:
    - job: build-key-handler-module  # Ensures the build job completes first
      artifacts: true

# Key handler containerize stage
containerize-key-handler-module:
  variables:
    MODULE: $KEY_HANDLER_MODULE
    DOCKER_FILE: $KEY_HANDLER_DOCKER_FILE
  extends:
    - .containerize-module
