# Service name
serviceName: user-manager

# Namespace
namespace: intervene-dev

# Environment-specific variables
env:
  profile: "gcp-dev-env"

# Replica count for development
replicaCount: 1

# Image details
image:
  repository: dockerhub.ebi.ac.uk/gdp/igs4eu-platform
  tagPrefix: user-manager
  tag: 0.0.1
  tagPostfix: dev
  pullPolicy: Always

# Service account
serviceAccount: gcp-service-api

# Application properties file
properties:
  fileName: "application-gcp-dev-env.properties"

# Kubernetes resource limits for development
resources:
  limits:
    cpu: "0.5"
    memory: "500Mi"
  requests:
    cpu: "0.5"
    memory: "300Mi"

# Java jvm memory size
java:
  maxSize: -Xmx256m

# GCP project details
gcp:
  projectName: "prj-ext-dev-intervene-413412"
  zone: "europe-west2"
  dbName: "intervene-dev"

# GCP cloud sql proxy resource
cloudSql:
  resources:
    limits:
      cpu: "0.5"
      memory: "500Mi"
    requests:
      cpu: "0.5"
      memory: "300Mi"

