apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{ .Values.properties.fileName | quote }}: |
    {{ .Files.Get (printf "files/%s" .Values.properties.fileName) | indent 4 }}
