apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{ printf "%s: |\n%s" .Values.properties.fileName (.Files.Get (printf "files/%s" .Values.properties.fileName) | indent 4) | indent 2 }}
