#####################################################################################
# Application config
#####################################################################################
server.port=8080
#####################################################################################
# Apache HttpClient Connection Configuration
#####################################################################################
webclient.connection.pipe-size=4096
webclient.connection.connection-timeout=5
webclient.connection.socket-timeout=0
webclient.connection.read-write-timeout=30000
#####################################################################################
# Download Configuration
#####################################################################################
file.download.buffer-size=4096
file.download.parallel.connections.max=3
file.download.parallel.file-size=200000
#####################################################################################
# File Download Retry
#####################################################################################
# EXPONENTIAL/FIXED
file.download.retry.strategy=FIXED
file.download.retry.attempts.max=3
# Exponential
file.download.retry.attempts.delay=1000
file.download.retry.attempts.maxDelay=30000
file.download.retry.attempts.multiplier=2
# Fixed
file.download.retry.attempts.back-off-period=2000
#####################################################################################
# OAuth Credentials
#####################################################################################
# EGA AAI
ega.aai.access-token.uri=https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
ega.aai.client-id=${EGA_AAI_CLIENT_ID}
ega.aai.client-secret=${EGA_AAI_CLIENT_SECRET}
ega.aai.scopes=openid
ega.aai.username=${EGA_AAI_USERNAME}
ega.aai.password=${EGA_AAI_PASSWORD}
# Globus AAI
globus.aai.access-token.uri=https://auth.globus.org/v2/oauth2/token
globus.aai.client-id=${GLOBUS_CLIENT_ID}
globus.aai.client-secret=${GLOBUS_CLIENT_SECRET}
globus.aai.scopes=openid,email,profile,urn:globus:auth:scope:transfer.api.globus.org:all
#####################################################################################
# Basic authentication
#####################################################################################
basic.auth.username=@basic.auth.username@
basic.auth.password=@basic.auth.password@
#####################################################################################
# EGA Config
#####################################################################################
ega.data-api.url=https://ega.ebi.ac.uk:8052
ega.file.storage.path=/data/gdp/ega/file/
#####################################################################################
# Globus Config
#####################################################################################
globus.managed-collection.endpoint-id=14a0be5f-226c-49fe-b65f-dba083d67fc3
globus.guest-collection.endpoint-id=73de49e6-2122-41b3-aea8-252c0d9e5f83
globus.guest-collection.home-path=/~/upload/intervene-igs4eu-platform-prod-env
globus.endpoint.mkdir.uri=/operation/endpoint/${globus.managed-collection.endpoint-id}/mkdir
globus.endpoint.access.uri=/endpoint/${globus.guest-collection.endpoint-id}/access
globus.endpoint.list-files.uri=/operation/endpoint/${globus.managed-collection.endpoint-id}/ls
globus.endpoint.list-files.limit=10
globus.endpoint.submission-id.uri=/submission_id
globus.endpoint.delete-dir.uri=/delete
globus.shared-endpoint.display-name=ebi#gdp#intervene#
globus.shared-endpoint.description=${globus.shared-endpoint.display-name}
globus.shared-endpoint.owner-string=IGS4EU Platform
globus.shared-endpoint.contact-email=ashutosh@ebi.ac.uk
globus.shared-endpoint.organization=EBI
globus.shared-endpoint.force-encryption=true
globus.data-api.url=https://transfer.api.globusonline.org/v0.10
globus.auth-api.url=https://auth.globus.org/v2/api
globus.auth-api.credentials=${GLOBUS_AUTH_API_CREDENTIALS}
#####################################################################################
# Platform config
#####################################################################################
pipeline-execution.platform=GCP
#####################################################################################
# Cloud storage config
#####################################################################################
cloud.gcp.project-id=prj-ext-dev-intervene-413412
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
#####################################################################################
# Logging config
#####################################################################################
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.file.handler=INFO
logging.level.org.apache.http=TRACE
logging.level.httpclient.wire=ERROR
logging.level.org.apache.commons.httpclient=ERROR
logging.level.org.apache.http.wire=ERROR
logging.level.org.apache.http.headers=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
#####################################################################################
# Internal service config
#####################################################################################
intervene.user-manager.base-url=http://user-manager.intervene-prod.svc.cluster.local:8080/user-manager
intervene.user-manager.user-account.uri=/user/account
