#####################################################################################
# Apache HttpClient Connection config
#####################################################################################
webclient.connection.pipe-size=4096
webclient.connection.connection-timeout=5
webclient.connection.socket-timeout=0
webclient.connection.read-write-timeout=30000
#####################################################################################
# Download config
#####################################################################################
file.download.buffer-size=4096
file.download.parallel.connections.max=3
file.download.parallel.file-size=200000
#####################################################################################
# File Download Retry
#####################################################################################
# EXPONENTIAL/FIXED
file.download.retry.strategy=FIXED
file.download.retry.attempts.max=3
# Exponential
file.download.retry.attempts.delay=1000
file.download.retry.attempts.maxDelay=30000
file.download.retry.attempts.multiplier=2
# Fixed
file.download.retry.attempts.back-off-period=2000
#####################################################################################
# OAuth Credentials
#####################################################################################
# EGA AAI
ega.aai.access-token.uri=https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
ega.aai.client-id=@ega.aai.client-id@
ega.aai.client-secret=@ega.aai.client-secret@
ega.aai.scopes=openid
ega.aai.username=@ega.aai.username@
ega.aai.password=@ega.aai.password@
# Globus AAI
globus.aai.access-token.uri=https://auth.globus.org/v2/oauth2/token
globus.aai.client-id=@globus.aai.client-id@
globus.aai.client-secret=@globus.aai.client-secret@
globus.aai.scopes=openid,email,profile,urn:globus:auth:scope:transfer.api.globus.org:all
#####################################################################################
# EGA config
#####################################################################################
ega.data-api.url=https://ega.ebi.ac.uk:8052
ega.file.storage.path=/data/gdp/ega/file/
#####################################################################################
# Globus config
#####################################################################################
globus.managed-collection.endpoint-id=14a0be5f-226c-49fe-b65f-dba083d67fc3
globus.guest-collection.endpoint-id=c1e6310c-11d5-4e8a-9443-211884f04c6f
globus.guest-collection.home-path=/~/upload/intervene-igs4eu-platform-dev-env
globus.endpoint.mkdir.uri=/operation/endpoint/${globus.managed-collection.endpoint-id}/mkdir
globus.endpoint.access.uri=/endpoint/${globus.guest-collection.endpoint-id}/access
globus.endpoint.list-files.uri=/operation/endpoint/${globus.managed-collection.endpoint-id}/ls
globus.shared-endpoint.display-name=ebi#gdp#intervene#
globus.shared-endpoint.description=${globus.shared-endpoint.display-name}
globus.shared-endpoint.owner-string=IGS4EU Platform
globus.shared-endpoint.contact-email=ashutosh@ebi.ac.uk
globus.shared-endpoint.organization=EBI
globus.shared-endpoint.force-encryption=true
globus.data-api.url=https://transfer.api.globusonline.org/v0.10
globus.auth-api.url=https://auth.globus.org/v2/api
globus.auth-api.credentials=@globus.auth-api.credentials@
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
#####################################################################################
# Logging config
#####################################################################################
logging.level.org.apache.http=TRACE
logging.level.httpclient.wire=ERROR
logging.level.org.apache.commons.httpclient=ERROR
logging.level.org.apache.http.wire=ERROR
logging.level.org.apache.http.headers=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO
#####################################################################################
# Spring config
#####################################################################################
spring.jackson.property-naming-strategy=SNAKE_CASE
