#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=igs4eu-file-handler
server.port=8080
spring.webflux.base-path=/file-handler
spring.profiles.active=${ENV:dev}
#####################################################################################
# Metrics Configuration
#####################################################################################
management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.observations.key-values.application=${spring.application.name}
