#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=igs4eu-file-handler
server.port=8080
server.servlet.context-path=/file-handler
spring.webflux.base-path=/file-handler
spring.profiles.active=${ENV:dev-env}
#####################################################################################
# Metrics Configuration
#####################################################################################
management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.metrics.tags.application=${spring.application.name}
