#####################################################################################
# Apache HttpClient Connection Configuration
#####################################################################################
webclient.connection.pipe-size=4096
webclient.connection.connection-timeout=5
webclient.connection.socket-timeout=0
webclient.connection.read-write-timeout=30000
#####################################################################################
# Download Configuration
#####################################################################################
file.download.buffer-size=4096
file.download.parallel.connections.max=3
file.download.parallel.file-size=200000
#####################################################################################
# File Download Retry
#####################################################################################
# EXPONENTIAL/FIXED
file.download.retry.strategy=FIXED
file.download.retry.attempts.max=3
# Exponential
file.download.retry.attempts.delay=1000
file.download.retry.attempts.maxDelay=30000
file.download.retry.attempts.multiplier=2
# Fixed
file.download.retry.attempts.back-off-period=2000
#####################################################################################
# EGA AAI OAuth Credentials
#####################################################################################
ega.aai.access-token.uri=https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
ega.aai.client-id=@ega.aai.client-id@
ega.aai.client-secret=@ega.aai.client-secret@
ega.aai.scopes=openid
ega.aai.username=@ega.aai.username@
ega.aai.password=@ega.aai.password@
ega.data-api.url=https://ega.ebi.ac.uk:8052
ega.file.storage.path=/data/gdp/ega/file/
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
#####################################################################################
# Logging Configuration
#####################################################################################
logging.level.org.apache.http=TRACE
logging.level.httpclient.wire=ERROR
logging.level.org.apache.commons.httpclient=ERROR
logging.level.org.apache.http.wire=ERROR
logging.level.org.apache.http.headers=INFO
logging.level.org.springframework.web=DEBUG
