#####################################################################################
# Application config
#####################################################################################
server.port=8080
#####################################################################################
# GCP config
#####################################################################################
gcp.project-id=prj-ext-prod-intervene-437413
gcp.secret.path-prefix=projects/204582653383/secrets
gcp.region=EUROPE_WEST2
gcp.secret-manager.config.ttl=2592000
#####################################################################################
# Crypt4gh config
#####################################################################################
crypt4gh.shell-path=/bin/bash -c
crypt4gh.binary-path=/opt/pipx/bin/crypt4gh-keygen
crypt4gh.keys.base-path=/home
crypt4gh.private-key.password=${SEC_KEY_PASSWD}
#####################################################################################
# Spring Security OAuth2 client registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
#####################################################################################
# Basic authentication
#####################################################################################
basic.auth.username=${BASIC_AUTH_USERNAME}
basic.auth.password=${BASIC_AUTH_PASSWORD}
#####################################################################################
# Internal service config
#####################################################################################
intervene.user-manager.base-url=http://user-manager.intervene-prod.svc.cluster.local:8080/user-manager
intervene.user-manager.user-account.uri=/user/account
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
