#####################################################################################
# Datasource configuration
#####################################################################################
datasource.pipeline-manager.url=jdbc:postgresql://localhost:5432/pspintervenepro?currentSchema=intervene
datasource.pipeline-manager.username=@datasource.pipeline-manager.username@
datasource.pipeline-manager.password=@datasource.pipeline-manager.password@
datasource.pipeline-manager.driver-class-name=org.postgresql.Driver
datasource.pipeline-manager.hikari.maximum-pool-size=3
datasource.pipeline-manager.hikari.minimum-idle=1
datasource.pipeline-manager.initialization-mode=embedded
# Hibernate
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
#####################################################################################
# Kafka Configuration
#####################################################################################
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.heartbeat.interval.ms=10000
spring.kafka.consumer.properties.session.timeout.ms=60000
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.concurrency=1
spring.kafka.producer.properties.linger.ms=1
#
kafka.pipeline-trigger.topic=pipeline-launch
kafka.pipeline-status.topic=pipeline-status
kafka.group.instance-id=pipeline-manager
kafka.listener.max.poll.interval.ms=3600000
kafka.listener.default.poll.timeout.ms=500000
