#####################################################################################
# Application config
#####################################################################################
server.port=8020
#####################################################################################
# Datasource config
#####################################################################################
datasource.pipeline-manager.host=@datasource.intervene.host@
datasource.pipeline-manager.username=@datasource.intervene.username@
datasource.pipeline-manager.password=@datasource.intervene.password@
datasource.pipeline-manager.port=5432
datasource.pipeline-manager.database=pspintervenepro
datasource.pipeline-manager.schema=intervene
datasource.pipeline-manager.ssl-mode=disable
datasource.pipeline-manager.driver-class-name=org.postgresql.Driver
datasource.pipeline-manager.hikari.maximum-pool-size=3
datasource.pipeline-manager.hikari.minimum-idle=1
datasource.pipeline-manager.initialization-mode=embedded
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
#####################################################################################
# Kafka config
#####################################################################################
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.heartbeat.interval.ms=10000
spring.kafka.consumer.properties.session.timeout.ms=60000
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.concurrency=1
spring.kafka.producer.properties.linger.ms=1
#
kafka.pipeline-launch.topic=pipeline-launch
kafka.pipeline-status.topic=pipeline-status
kafka.group.instance-id=pipeline-manager
kafka.listener.max.poll.interval.ms=3600000
kafka.listener.default.poll.timeout.ms=500000
#####################################################################################
# Internal service config
#####################################################################################
intervene.file-handler.base-url=http://localhost:8010/file-handler
intervene.file-handler.globus.user-details.uri=/globus/user
intervene.file-handler.globus.list-files-dir.uri=/globus/guest-collection
intervene.file-handler.globus.create-dir.uri=/globus/guest-collection
intervene.user-manager.base-url=http://localhost:8030/user-manager
intervene.user-manager.user-account.uri=/user/account
intervene.user-manager.user-account.consent-data.uri=${intervene.user-manager.user-account.uri}/consent/data
intervene.key-handler.base-url=http://localhost:8040/key-handler
intervene.key-handler.keys.uri=/key
intervene.pipeline-request.base-url=http://localhost:6060
intervene.pipeline-request.uri=/launch
#####################################################################################
# Cloud storage config
#####################################################################################
# S3
## Embassy
ebi-embassy.s3.endpoint=https://uk1s3.embassy.ebi.ac.uk
ebi-embassy.s3.credentials.access-key=@ebi-embassy.s3.credentials.access-key@
ebi-embassy.s3.credentials.secret-key=@ebi-embassy.s3.credentials.secret-key@
ebi-embassy.s3.credentials.region=@ebi-embassy.s3.credentials.region@
## Allas
allas.s3.endpoint=https://a3s.fi
allas.s3.credentials.access-key=@allas.s3.credentials.access-key@
allas.s3.credentials.secret-key=@allas.s3.credentials.secret-key@
allas.s3.credentials.region=@allas.s3.credentials.region@
# Cloud storage config
cloud.gcp.project-id=prj-ext-dev-intervene-413412
cloud.storage.bucket-name-format=intervene-dev-%s-results
cloud.storage.bucket-prefix=results/%s/score
#####################################################################################
# Email config
#####################################################################################
spring.mail.host=outgoing.intervenegeneticscores.org
spring.mail.port=587
spring.mail.username=@intervene.email.username@
spring.mail.password=@intervene.email.password@
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
#####################################################################################
# Message gateway config
#####################################################################################
pipeline-request.mode=KAFKA
#pipeline-request.mode=HTTP
#pipeline-request.mode=S3
pipeline-execution.platform=GCP
#####################################################################################
# Basic authentication Config
#####################################################################################
basic.auth.username=@basic.auth.username@
basic.auth.password=@basic.auth.password@
#####################################################################################
# User manager auth
#####################################################################################
user-manager.basic.auth=@user-manager.basic.auth@
#####################################################################################
# Redis Config
#####################################################################################
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.client-type=lettuce
redis.pgs-ids.key-prefix=pgs_ids_set
redis.pud-data.key-prefix=pub_data_set
#####################################################################################
# Jackson Config
#####################################################################################
jackson.date-format=yyyy-MM-dd HH:mm:ss
#####################################################################################
# Platform Config
#####################################################################################
intervene.platform.url=https://dev.intervenegeneticscores.org/pgs-calculator/result?pipelineId=%s
#####################################################################################
# Logging config
#####################################################################################
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.pipeline.manager=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
#####################################################################################
# PGS Catalog config
#####################################################################################
pgs-catalog.rest.base-url=https://www.pgscatalog.org
pgs-catalog.rest.search-url=/rest/trait/search
