#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=igs4eu-pipeline-manager
server.port=8090
server.servlet.context-path=/api
spring.profiles.active=${ENV:dev-env}
