apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgs-ids-pub-data-updated-date-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: standard
