#####################################################################################
# Application config
#####################################################################################
server.port=8080
#####################################################################################
# Datasource config
#####################################################################################
datasource.pipeline-manager.host=127.0.0.1
datasource.pipeline-manager.username=${DB_USERNAME}
datasource.pipeline-manager.password=${DB_PASSWORD}
datasource.pipeline-manager.port=5432
datasource.pipeline-manager.database=intervene-test
datasource.pipeline-manager.schema=geneticscoresplatform
datasource.pipeline-manager.ssl-mode=disable
datasource.pipeline-manager.driver-class-name=org.postgresql.Driver
datasource.pipeline-manager.hikari.maximum-pool-size=3
datasource.pipeline-manager.hikari.minimum-idle=1
datasource.pipeline-manager.initialization-mode=embedded
#####################################################################################
# Database config
#####################################################################################
expired-dataset.batch-size=50
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.aai.lifescience-ri.eu/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.aai.lifescience-ri.eu/oidc/jwk
#####################################################################################
# Kafka config
#####################################################################################
spring.kafka.bootstrap-servers=kafka-cluster-kafka-brokers.kafka-test.svc.cluster.local:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.heartbeat.interval.ms=10000
spring.kafka.consumer.properties.session.timeout.ms=60000
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.concurrency=1
spring.kafka.producer.properties.linger.ms=1
#
kafka.pipeline-launch.topic=pipeline-launch
kafka.pipeline-status.topic=pipeline-status
kafka.group.instance-id=pipeline-manager
kafka.listener.max.poll.interval.ms=3600000
kafka.listener.default.poll.timeout.ms=500000
#####################################################################################
# Internal Service config
#####################################################################################
intervene.file-handler.base-url=http://file-handler.intervene-test.svc.cluster.local:8080/file-handler
intervene.file-handler.globus.user-details.uri=/globus/user
intervene.file-handler.globus.list-files-dir.uri=/globus/guest-collection
intervene.file-handler.globus.create-dir.uri=/globus/guest-collection
intervene.file-handler.globus.delete-dir.uri=/globus/guest-collection
intervene.file-handler.cloud.list-files.uri=/cloud/storage/files
intervene.file-handler.cloud.stream-files.uri=/cloud/storage/stream-file
intervene.user-manager.base-url=http://user-manager.intervene-test.svc.cluster.local:8080/user-manager
intervene.user-manager.user-account.uri=/user/account
intervene.user-manager.user-account.consent-data.uri=${intervene.user-manager.user-account.uri}/consent/data
intervene.key-handler.base-url=http://key-handler.intervene-test.svc.cluster.local:8080/key-handler
intervene.key-handler.keys.uri=/key
intervene.pipeline-request.base-url=http://hattivatti.intervene-test.svc.cluster.local:80
intervene.pipeline-request.uri=/launch
#####################################################################################
# Cloud storage config
#####################################################################################
# S3
## Embassy
ebi-embassy.s3.endpoint=https://uk1s3.embassy.ebi.ac.uk
ebi-embassy.s3.credentials.access-key=${EMBASSY_S3_ACCESS_KEY_ID}
ebi-embassy.s3.credentials.secret-key=${EMBASSY_S3_SECRET_ACCESS_KEY}
ebi-embassy.s3.credentials.region=us-east-1
## Allas
allas.s3.endpoint=https://a3s.fi
allas.s3.credentials.access-key=${ALLAS_S3_ACCESS_KEY_ID}
allas.s3.credentials.secret-key=${ALLAS_S3_SECRET_ACCESS_KEY}
allas.s3.credentials.region=US
# Cloud storage config
cloud.gcp.project-id=prj-ext-test-intervene-448616
cloud.storage.bucket-name-format=intervene-test-%s-results
cloud.storage.bucket-prefix=results/%s/score
#####################################################################################
# Email config
#####################################################################################
spring.mail.host=outgoing.geneticscores.org
spring.mail.port=587
spring.mail.username=${INTERVENE_EMAIL_ID}
spring.mail.password=${INTERVENE_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
# Thymeleaf email template
spring.thymeleaf.prefix=file:/application/config/email/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
#####################################################################################
# Message Gateway config
#####################################################################################
pipeline-request.mode=KAFKA
pipeline-execution.platform=GCP
#####################################################################################
# Basic Authentication Configuration
#####################################################################################
basic.auth.username=${BASIC_AUTH_USERNAME}
basic.auth.password=${BASIC_AUTH_PASSWORD}
#####################################################################################
# User manager auth
#####################################################################################
user-manager.basic.auth=${USER_MANAGER_BASIC_AUTH}
file-handler.basic.auth=${FILE_HANDLER_BASIC_AUTH}
#####################################################################################
# Redis config
#####################################################################################
spring.data.redis.host=redis.intervene-test.svc.cluster.local
spring.data.redis.port=6379
spring.data.redis.client-type=lettuce
redis.pgs-ids.key-prefix=pgs_ids_set
redis.pud-data.key-prefix=pub_data_set
#####################################################################################
# Jackson config
#####################################################################################
jackson.date-format=dd-MM-yyyy HH:mm:ss
#####################################################################################
# Platform config
#####################################################################################
intervene.platform.url=https://gcp.geneticscores.org/pgs-calculator/result?pipelineId=%s
#####################################################################################
# Logging config
#####################################################################################
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.pipeline.manager=INFO
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=INFO
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
#####################################################################################
# PGS Catalog config
#####################################################################################
pgs-catalog.rest.base-url=https://www.pgscatalog.org
pgs-catalog.rest.search-url=/rest/trait/search
#####################################################################################
# Swagger config
#####################################################################################
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml
#####################################################################################
# Pipeline config
#####################################################################################
pipeline.limit.per-day.per-user=30
