#####################################################################################
# Datasource configuration
#####################################################################################
datasource.user-manager.url=jdbc:postgresql://postgres-db-lb.intervene-dev.svc.cluster.local:5432/pspintervenepro?currentSchema=intervene
datasource.user-manager.username=@datasource.user-manager.username@
datasource.user-manager.password=@datasource.user-manager.password@
datasource.user-manager.driver-class-name=org.postgresql.Driver
datasource.user-manager.hikari.maximum-pool-size=3
datasource.user-manager.hikari.minimum-idle=1
datasource.user-manager.initialization-mode=embedded
# Hibernate
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
#####################################################################################
# Elixir RestTemplate Configuration
#####################################################################################
elixir.oidc.url=https://login.elixir-czech.org/oidc/
elixir.oidc.request.connection.timeout=30
elixir.oidc.request.read.timeout=30
#####################################################################################
# Log Configuration
#####################################################################################
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.user.manager=INFO
