#####################################################################################
# Application config
#####################################################################################
server.port=8030
#####################################################################################
# Datasource config
#####################################################################################
datasource.user-manager.host=@datasource.intervene.host@
datasource.user-manager.username=@datasource.intervene.username@
datasource.user-manager.password=@datasource.intervene.password@
datasource.user-manager.port=5432
datasource.user-manager.database=intervene-dev
datasource.user-manager.schema=geneticscoresplatform
datasource.user-manager.ssl-mode=disable
datasource.user-manager.driver-class-name=org.postgresql.Driver
datasource.user-manager.hikari.maximum-pool-size=3
datasource.user-manager.hikari.minimum-idle=1
datasource.user-manager.initialization-mode=embedded
#####################################################################################
# OIDC config
#####################################################################################
oidc.user-info.uri=/userinfo
#####################################################################################
# Spring Security OAuth2 Client Registration
#####################################################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.elixir-czech.org/oidc/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.elixir-czech.org/oidc/jwk
#####################################################################################
# Elixir RestTemplate config
#####################################################################################
elixir.oidc.url=https://login.elixir-czech.org/oidc/
elixir.oidc.request.connection.timeout=30
elixir.oidc.request.read.timeout=30
#####################################################################################
# Log config
#####################################################################################
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.root=INFO
logging.level.uk.ac.ebi.gdp.intervene.user.manager=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework.security=INFO
#####################################################################################
# Metrics
#####################################################################################
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.baggage.correlation.enabled=true
#####################################################################################
# Basic authentication
#####################################################################################
basic.auth.username=@basic.auth.username@
basic.auth.password=@basic.auth.password@
#####################################################################################
# Reactor config
#####################################################################################
spring.reactor.context-propagation=auto
#####################################################################################
# Swagger config
#####################################################################################
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml

