#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=igs4eu-user-manager
server.port=8080
server.servlet.context-path=/user-manager
spring.webflux.base-path=/user-manager
spring.profiles.active=${ENV:dev-env}
