#####################################################################################
# Application Configuration
#####################################################################################
spring.application.name=igs4eu-user-manager
server.port=8090
server.servlet.context-path=/user
spring.profiles.active=${ENV:dev-env}
